"""
Post-OCR word-level corrections for Arabic Tesseract output.

apply_word_corrections(text, extra=None) performs whole-word substitutions
using a regex built from WORD_CORRECTIONS merged with any caller-supplied dict.

Design constraints:
- Only correct tokens that are clearly OCR artefacts (not valid Arabic words).
- Never silently corrupt correct output: when in doubt, omit the correction.
- Word boundaries use \\b-equivalent anchors for Arabic (zero-width assertions
  between Arabic letters and non-Arabic characters).
"""

import re

# ---------------------------------------------------------------------------
# Base corrections — general Tesseract/Arabic OCR artefacts
# ---------------------------------------------------------------------------
# Each entry maps an OCR token that is NOT a valid Arabic word to its correct
# form. Tokens that ARE valid words (e.g. 'ان', 'فان') are excluded even if
# they frequently appear in error, because the risk of false positives is too
# high without context.

WORD_CORRECTIONS: dict[str, str] = {
    # 'قِ' is not a word; Tesseract reads 'في' (in/at) as 'قِ' — very reliable
    "قِ": "في",
    "قٍ": "في",
}

# ---------------------------------------------------------------------------
# Ground-truth-derived corrections for Preface.pdf
# Generated by analyse_confusables.py from samples/Preface_1-10.txt.
# Only includes tokens that appear ≥2× in the aligned error set AND are
# clearly OCR artefacts (not valid standalone Arabic words).
# ---------------------------------------------------------------------------
GT_DERIVED_CORRECTIONS: dict[str, str] = {
    "العكري":  "العسكري",   # dropped sīn — not a real word
    "خلاها":   "خلالها",    # dropped lam — not a real word
}

# ---------------------------------------------------------------------------
# Compiled pattern cache
# ---------------------------------------------------------------------------
_ARABIC = re.compile(r'[؀-ۿً-ٟـ]')

def _build_pattern(corrections: dict[str, str]) -> re.Pattern | None:
    if not corrections:
        return None
    # Sort longest first to avoid partial-match shadowing
    keys = sorted(corrections, key=len, reverse=True)
    # Arabic "word boundary": preceded/followed by non-Arabic or start/end
    escaped = [re.escape(k) for k in keys]
    pattern = r'(?<![؀-ۿً-ٟـ])(?:' + '|'.join(escaped) + r')(?![؀-ۿً-ٟـ])'
    return re.compile(pattern)


def apply_word_corrections(
    text: str,
    extra: dict[str, str] | None = None,
    include_gt_derived: bool = False,
) -> str:
    """
    Apply word-level OCR corrections to *text*.

    Parameters
    ----------
    text:
        Raw or lightly post-processed OCR output.
    extra:
        Caller-supplied additional corrections (merged on top of the base set).
    include_gt_derived:
        Include the ground-truth-derived dictionary (Preface.pdf–specific).
        Useful when processing that specific book; off by default.
    """
    combined: dict[str, str] = dict(WORD_CORRECTIONS)
    if include_gt_derived:
        combined.update(GT_DERIVED_CORRECTIONS)
    if extra:
        combined.update(extra)

    pat = _build_pattern(combined)
    if pat is None:
        return text

    return pat.sub(lambda m: combined[m.group(0)], text)
